server:
  host: "0.0.0.0"
  http_port: 9090
  sse_port: 9091
  pg_url: "postgres://postgres:123456@localhost:5432/chat"
  file_dir: "./files"
auth:
  sign_key: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIERBny4CI/esbYEMIhLN+4PhU6pqUluqeIdIDtSnNEwK
    -----END PRIVATE KEY-----
  verify_key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAbHu3/n9PTtFlJKjAekJimObV19GtEOTlNvqTVvv4ZPY=
    -----END PUBLIC KEY-----
