server:
  host: "0.0.0.0"
  http_port: 9090
  sse_port: 9091
  pg_url: "postgres://postgres:123456@localhost:5432/chat"
  file_dir: "chat/files"
auth:
  sign_key: |
    -----BEGIN PRIVATE KEY-----
    MC4CAQAwBQYDK2VwBCIEIMnlSXiv8bTSgHwsuyEynQBsX6i4PtvW8n9/I55CmtPE
    -----END PRIVATE KEY-----
  verify_key: |
    -----BEGIN PUBLIC KEY-----
    MCowBQYDK2VwAyEAFxNBlNS2fA6RCtuXQFhIbz/pri8MEqmWFpdTezEAbmI=
    -----END PUBLIC KEY-----
