server:
  host: 0.0.0.0
  crm_gateway_port: 50000
  user_stat_port: 50001
  metadata_port: 50002
  notify_port: 50003

  from: crm@acme.org
  user_stat_url: http://localhost:50001
  metadata_url: http://localhost:50002
  notify_url: http://localhost:50003

  pg_url: postgres://postgres:123456@localhost:5432/stats
auth:
  verify_key: "verify-key"
