[package]
name = "taotie"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
anyhow = { workspace = true }
arrow = { version = "57.1.0", features = ["prettyprint"] }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
